version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: 80
            DATABASE_URL: http://postgres:root@db:5432/app
        volumes:
            - ./src:/var/www/html/
        ports:
            - 80:80
    db:
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: root
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data: