version: '3'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: 80
        volumes:
            - ./src:/var/www/html/
        ports:
            - 80:80
    mysql:
        image: mariadb:10.4.12
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data: